added more scripts. more cleanup. more refinement. more more more!

diff --git a/theme-hook b/theme-hook
--- a/theme-hook
+++ b/theme-hook
@@ -5,24 +5,23 @@ error() {
     exit 1
 }
 
-# execute core omarchy recipe hooks
+# execute core omarchy recipe recipes
 if [[ -d /etc/omarchy/recipes.d ]]; then
-  for hook in /etc/omarchy/recipes.d/*.sh; do
-    if [[ -f "$hook" && -x "$hook" ]]; then
-      if ! "$hook"; then
-          error "$(basename "$hook") failed!" >&2
+  for recipe in /etc/omarchy/recipes.d/*.sh; do
+    if [[ -f "$recipe" && -x "$recipe" ]]; then
+      if ! "$recipe"; then
+          error "$(basename "$recipe") failed!" >&2
       fi
     fi
   done
 fi
 
-# execute user recipe hooks
-# TODO: make this an absolute path to xdg-user recipes folder
-if [[ -d ./recipes.d ]]; then
-  for hook in ./recipes.d/*.sh; do
-    if [[ -f "$hook" && -x "$hook" ]]; then
-      if ! "$hook"; then
-          error "$(basename "$hook") failed!" >&2
+# execute user recipe recipes
+if [[ -d $HOME/.config/omarchy/recipes.d/ ]]; then
+  for recipe in $HOME/.config/omarchy/recipes.d/*.sh; do
+    if [[ -f "$recipe" && -x "$recipe" ]]; then
+      if ! "$recipe"; then
+          error "$(basename "$recipe") failed!" >&2
       fi
     fi
   done
