added check for local scripts too; should help keep things easier for debugging/testing

diff --git a/theme-set b/theme-set
--- a/theme-set
+++ b/theme-set
@@ -119,3 +119,13 @@ if [[ -d ~/.config/omarchy/hooks/theme-set.d ]]; then
     fi
   done
 fi
+
+if [[ -d ./theme-set.d ]]; then
+  for hook in ./theme-set.d/*.sh; do
+    if [[ -f "$hook" && -x "$hook" ]]; then
+      if ! "$hook" "$@"; then
+          error "Hook $(basename "$hook") failed!" >&2
+      fi
+    fi
+  done
+fi
